### ISSUE TITLE
CMake improvements for GridTools 2.0

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1404]
- [x] Always compile double/float (with prefix for the test)
- [x] add tests individually instead of fetching, with possibility to select the backend (all backend specific tests always active, if requirements are available, e.g CUDA)
- [x] if build as subproject: don't enable new languages (Fortran or CUDA)
- [x] if build as subproject: disable tests by default, allow for opt-in
- [x] remove cpp_bindgen legacy (still have the dependency for tests)
- [x] #1395 
- [x] #1412 
- [x] _depends_on issues a warning if target doesn't exist

### TODO from #1421
- [x] cpp_bindgen example (move or fetch cpp_bindgen?)
- [x] Add flags to force some options (e.g. OpenMP, CUDA, maybe HIP)
- [x] Add test to ensure cuda storage is usable with host compiler (only cudart available)
- [x] Rename target `gridtools_cuda` to `gridtools_gpu`? as it is also used for hip? alias could be created to point to `gridtools_cuda` or `gridtools_hip` respectively.
- [x] Cleanup python build driver (remove switches floating point precision, structured/icosahedral etc)
- [x] Move to CMake 3.17.0? No
- [x] Sort out which targets we want to export and specify the dependencies clearly (e.g. storage_cuda vs backend_cuda), rename to gpu?

Add CMake tests to ensure that the following works
- [x] Clang in cuda mode
- [x] ~~Clang in nvcc mode (prefer-clang=OFF), but nvcc not compatible with clang version~~
- [x] Clang in nvcc mode with compatible clang

**Comment by havogt** [comment]
### TODO from #1421
- [ ] cpp_bindgen example (move or fetch cpp_bindgen?)
- [ ] Add flags to force some options (e.g. OpenMP, CUDA, maybe HIP)
- [ ] Add test to ensure cuda storage is usable with host compiler (only cudart available)
- [ ] Rename target `gridtools_cuda` to `gridtools_gpu`? as it is also used for hip? alias could be created to point to `gridtools_cuda` or `gridtools_hip` respectively.
- [ ] Cleanup python build driver (remove switches floating point precision, structured/icosahedral etc)
- [ ] Move to CMake 3.17.0?
- [ ] Sort out which targets we want to export and specify the dependencies clearly (e.g. storage_cuda vs backend_cuda), rename to gpu?

Add CMake tests to ensure that the following works
- [ ] Clang in cuda mode
- [ ] ~~Clang in nvcc mode (prefer-clang=OFF), but nvcc not compatible with clang version~~
- [ ] Clang in nvcc mode with compatible clang

**Comment by havogt** [comment]
All remaining issues are tracked in separate issues.
